[workspace]
members = [".", "package-managers", "package-manager-derive"]

[package]
name = "iwant"
version = "0.1.1"
authors = ["Collide <three-dim-sky@foxmail.com>"]
edition = "2021"
description = "Install applications what I WANT."
repository = "https://github.com/TD-Sky/iwant"
license = "MIT"
keywords = ["package-management"]
categories = ["command-line-utilities"]
readme = "README.md"

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0.26", features = ["derive"] }
serde = { version = "1.0.147", features = ["derive"] }
tabled = "0.10.0"
thiserror = "1.0.38"
package-managers = { path = "package-managers" }
toml = "0.7.2"
parse-display = { version = "0.8.0", default-features = false }

[build-dependencies]
clap = { version = "4.0.26", features = ["derive"] }
clap_complete = "4.0.5"
clap_complete_nushell = "0.1.8"

[[bin]]
name = "iwant"
path = "src/main.rs"

[profile.release]
strip = true
lto = true
