[workspace]
members = [".", "package-managers", "package-manager-derive"]

[package]
name = "iwant"
version = "0.2.2"
authors = ["Collide <three-dim-sky@foxmail.com>"]
edition = "2021"
description = "Install applications what I WANT."
repository = "https://github.com/TD-Sky/iwant"
license = "MIT"
keywords = ["package-management"]
categories = ["command-line-utilities"]
readme = "README.md"

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.3.3", features = ["derive"] }
serde = { version = "1.0.164", features = ["derive"] }
tabled = { version = "0.12.2", features = ["color"] }
thiserror = "1.0.40"
package-managers = { path = "package-managers" }
toml = "0.7.4"
parse-display = { version = "0.8.1", default-features = false }
terminal_size = "0.2.6"
owo-colors = "3.5.0"

[build-dependencies]
clap = { version = "4.3.3", features = ["derive"] }
clap_complete = "4.3.1"
clap_complete_nushell = "4.3.1"

[[bin]]
name = "iwant"
path = "src/main.rs"

[profile.release]
strip = true
lto = true
